spring:
  application:
    name: DocumentManagementSystem
  jackson:
    serialization:
      write_dates_as_timestamps: false
kafka:
  topic: ${KAFKA_TOPIC:document-management-topic}
  group-id: document-group

